- name: Loops demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      debug:
        msg: Fruit Name - {{ item }}
      loop:
        - Apple
        - Pineapple
        - Banana
        - Grapes

